
services:
  consul.diwakar:
    container_name: consul
    image: hashicorp/consul:1.20
    ports:
      - "8500:8500"
    networks:
      - web


  micro-1.diwakar:
    container_name: micro-1
    build: ./micro-1
    networks:
      - web

  micro-2.diwakar:
    container_name: micro-2
    build: ./micro-2
    ports:
      - "8083:80"
    networks:
      - web

networks:
  web:
    driver: bridge